version: "3.9"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "newuser"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U newuser -d test
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: flask --app main run --host 0.0.0.0 --port 5000
