version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "newuser"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      CREATE ROLE newuser WITH CREATEDB LOGIN PASSWORD 'password'
      CREATE DATABASE test WITH OWNER newuser;
